---
collections:
  - name: community.vmware
  - name: community.windows
  - name: awx.awx
  - name: amazon.aws
  - name: fortinet.fortios
  - name: ansible.windows
  - name: azure.azcollection
  - name: somaz94.ansible_k8s_iac_tool
  - name: google.cloud
  - name: kubernetes.core
  - name: kubevirt.core
  - name: openstack.cloud
  - name: redhatinsights.insights
  - name: theforeman.foreman
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: cisco.mso
  - name: cisco.aci
  - name: community.general
  - name: community.mysql
  - name: community.postgresql
  - name: fortinet.fortios
  - name: pureport.pureport
  - name: f5networks.f5_modules
  - name: community.general
  - name: microsoft.ad
  - name: codeaffen.phpipam
